1) Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [4]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


2) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


3) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [9]:
x = np.array([[1,2],[2,3]])
print("Sum of all elements")
print(np.sum(x))
print("sum of each column ")
print(np.sum(x, axis=0))
print("sum of each row")
print(np.sum(x, axis=1))

Sum of all elements
8
sum of each column 
[3 5]
sum of each row
[3 5]


4) Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [12]:
x = np.array([1,2])
y = np.array([3,4])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))


[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]


5) Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [13]:
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
